name       : arduino
version    : 1.8.10
release    : 2
source     :
    - https://github.com/arduino/Arduino/archive/1.8.10.tar.gz : 9b0ab3de8d8b95d67c74dba6b34c84a6842576c56ab521490455f21ee1e3f043
    - https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/releases/download/v0.10.9/WiFi101-Updater-ArduinoIDE-Plugin-0.10.9.zip : b9067c0a345576a5a5b8d3c6c67fb0a09291659df57baa83978f686ebdc78534
    - https://downloads.arduino.cc/libastylej-2.05.1-4.zip : 3a8d98e85c344ca945790f05ff8b1b0f2a3cfcc2939001e58f47ad5ed03a6060
    - https://downloads.arduino.cc/liblistSerials/liblistSerials-1.4.2.zip : 75a89f408f3ecd4796ac173eaddd3c7e55021af030aee7f85b59a4190459a8dc
    - https://downloads.arduino.cc/cores/avr-1.6.23.tar.bz2 : 18618d7f256f26cd77c35f4c888d5d1b2334f07925094fdc99ac3188722284aa
    - https://github.com/arduino/arduino-builder/releases/download/1.4.4/arduino-builder-1.4.4.tar.xz : 2a895be601efed806936c009c5b79e7f43f802123ebc2ae73a4ecc8b46563662
    - https://github.com/arduino/ctags/releases/download/5.8-arduino11/ctags-5.8-arduino11.tar.xz : 9591ce86efa2ff7c277561706e6ace376201c5ec5f0b3925c50884ebf365d7e7
license    : GPL-2.0-or-later
component  : programming.ide
summary    : Arduino IDE
description: |
    The Arduino integrated development environment (IDE) is a cross-platform application written in the programming language Java.
    It is used to write and upload programs to Arduino compatible boards, but also, with the help of 3rd party cores,
    other vendor development boards.
strip      : no
networking : yes
builddeps  :
    - openjdk-8
    - apache-ant
    - unzip
    - golang
    - git
rundeps    :
    - openjdk-8
    - avr-libc
    - avrdude
environment: |
    export PREFIX=/usr/share/arduino
    export GOPATH="$workdir/build"
    export HARDWARE_DIR=$workdir/build/linux/work/hardware/arduino
    export BUILDER_DIR=$workdir/build/src/github.com/arduino/arduino-builder
    export CTAGS_DIR=$workdir/build/ctags
    export CTAGS_VERSION=ctags-5.8-arduino11
setup      : |
    # copy dependency libraries
    cp $sources/WiFi101-Updater-ArduinoIDE-Plugin-0.10.9.zip $workdir/build/shared/
    cp $sources/libastylej-2.05.1-4.zip $workdir/build/
    cp $sources/liblistSerials-1.4.2.zip $workdir/build/

    # unpack and patch ArduinoCore-avr to use system avr toolchain and avrdude
    mkdir -p $HARDWARE_DIR
    tar xCjv $HARDWARE_DIR -f $sources/avr-1.6.23.tar.bz2
    %patch -p1 < $pkgfiles/0001-use-system-toolchain.patch -d $HARDWARE_DIR/avr

    # unpack arduino-builder source
    mkdir -p $BUILDER_DIR
    tar xCv $BUILDER_DIR -f $sources/arduino-builder-1.4.4.tar.xz --strip-components=1

    # unpack arduino-ctags source
    mkdir -p $CTAGS_DIR
    tar xCv $CTAGS_DIR -f $sources/$CTAGS_VERSION.tar.xz --strip-components=1
build      : |
    cd build
    ant dist -Dversion=%version% build \
            -Dlight_bundle=true \
            -Dno_docs=true \
            -Dlocal_sources=false \
            -Dno_arduino_builder=true

    # install golang dependencies for building arduino-builder
    go get github.com/go-errors/errors
    go get github.com/stretchr/testify
    go get github.com/jstemmer/go-junit-report
    go get -u github.com/arduino/go-properties-map
    go get -u github.com/arduino/go-timeutils
    go get google.golang.org/grpc
    go get github.com/golang/protobuf/proto
    go get golang.org/x/net/context
    go get github.com/fsnotify/fsnotify
    go get github.com/schollz/closestmatch
    # build arduino-builder
    go build github.com/arduino/arduino-builder/arduino-builder

    # build arduino-ctags
    cd $CTAGS_DIR
    %configure
    %make
install    : |
    # install arduino ide
    install -dm00755 $installdir$PREFIX
    cp -a build/linux/work/* $installdir$PREFIX

    # install arduino-builder
    cp build/arduino-builder $installdir$PREFIX
    cp -a $BUILDER_DIR/hardware/* $installdir$PREFIX/hardware

    # install arduino-ctags
    cd $CTAGS_DIR
    install -dm00755 $installdir$PREFIX/tools-builder/ctags/$CTAGS_VERSION
    cp ctags $installdir$PREFIX/tools-builder/ctags/$CTAGS_VERSION/

    # remove empty dirs and unnecessary install/uninstall scripts
    rm -rf $installdir$PREFIX/{reference,hardware/arduino/avr/extras,install.sh,uninstall.sh,arduino-linux-setup.sh}

    # make symlink and .desktop file for arduino
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/usr/share/pixmaps
    install -dm00755 $installdir/usr/share/applications
    ln -s $PREFIX/arduino $installdir/usr/bin/arduino
    ln -s $PREFIX/lib/icons/256x256/apps/arduino.png $installdir/usr/share/pixmaps/arduino.png
    sed -i "s,<BINARY_LOCATION>,arduino %U,g;s,<ICON_NAME>,arduino,g" $installdir$PREFIX/lib/desktop.template
    mv $installdir$PREFIX/lib/desktop.template $installdir/usr/share/applications/arduino.desktop
