name       : arduino
version    : 1.8.19
release    : 10
source     :
    - https://github.com/arduino/Arduino/archive/1.8.19.tar.gz : 17839eb2a9bc7aeed3bb2a315898efdb3075ed605f98210b4a2d3b54199cc571
    - https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/releases/download/v0.12.0/WiFi101-Updater-ArduinoIDE-Plugin-0.12.0.zip : e9133b4abfed9393d57a89e1cda6ba5af45acfeedabfe32149828f0229da3a48
    - https://downloads.arduino.cc/libastylej-2.05.1-5.zip : def22874099c28d482720ee2a444ec4709f0980bae41f3ebb6033bbc79beb486
    - https://downloads.arduino.cc/liblistSerials/liblistSerials-1.4.2-2.zip : a338d470822de19bd971bd7a71d43f5273ba082baa9236be28c44b47c3e51f6b
    - https://downloads.arduino.cc/cores/avr-1.8.5.tar.bz2 : ca22143a3f5d32c4b693211d99aedce358e2e0a2ab90a58c05d3afc1b56436a4
    - https://github.com/arduino/arduino-builder/releases/download/1.6.1/arduino-builder-1.6.1.tar.xz : 7b22d5307592da8535e3425d24a09f2513019a7bb9f1056c252ab3c476a89d70
    - https://github.com/arduino/ctags/releases/download/5.8-arduino11/ctags-5.8-arduino11.tar.xz : 9591ce86efa2ff7c277561706e6ace376201c5ec5f0b3925c50884ebf365d7e7
    - https://github.com/arduino/arduino-examples/archive/refs/tags/1.9.1.zip : 900c4885843c3f650b4f34308ba6d45d7117279de628d810c6ec17dd06213684
license    : GPL-2.0-or-later
component  : programming.ide
summary    : Arduino IDE
description: |
    The Arduino integrated development environment (IDE) is a cross-platform application written in the programming language Java.
    It is used to write and upload programs to Arduino compatible boards, but also, with the help of 3rd party cores,
    other vendor development boards.
strip      : no
networking : yes
builddeps  :
    - apache-ant
    - unzip
    - golang
    - git
rundeps    :
    - openjdk-11
    - avr-libc
    - avrdude
environment: |
    export PREFIX=/usr/share/arduino
    export HARDWARE_DIR=$workdir/build/linux/work/hardware/arduino
    export BUILDER_DIR=$workdir/build/arduino-builder
    export CTAGS_DIR=$workdir/build/ctags
    export CTAGS_VERSION=ctags-5.8-arduino11
setup      : |
    %patch -p1 < $pkgfiles/use-openjdk-11.patch

    # copy dependency libraries
    cp $sources/WiFi101-Updater-ArduinoIDE-Plugin-0.12.0.zip $workdir/build/shared/
    cp $sources/libastylej-2.05.1-5.zip $workdir/build/
    cp $sources/liblistSerials-1.4.2-2.zip $workdir/build/
    cp $sources/1.9.1.zip $workdir/build/arduino-examples-1.9.1.zip

    # unpack and patch ArduinoCore-avr to use system avr toolchain and avrdude
    mkdir -p $HARDWARE_DIR/avr
    tar xCjv $HARDWARE_DIR/avr -f $sources/avr-1.8.5.tar.bz2 --strip-components=1
    %patch -p1 < $pkgfiles/0001-use-system-toolchain.patch -d $HARDWARE_DIR/avr
    rm -rf $HARDWARE_DIR/avr/drivers $HARDWARE_DIR/avr/post_install.bat

    # unpack arduino-builder source
    mkdir -p $BUILDER_DIR
    tar xCv $BUILDER_DIR -f $sources/arduino-builder-1.6.1.tar.xz --strip-components=1

    # unpack arduino-ctags source
    mkdir -p $CTAGS_DIR
    tar xCv $CTAGS_DIR -f $sources/$CTAGS_VERSION.tar.xz --strip-components=1
build      : |
    cd build
    ant dist -Dversion=%version% build \
            -Dlight_bundle=true \
            -Dno_docs=true \
            -Dlocal_sources=true \
            -Dno_arduino_builder=true

    # build arduino-builder
    cd $BUILDER_DIR
    go build

    # build arduino-ctags
    cd $CTAGS_DIR
    %configure
    %make
install    : |
    # install arduino ide
    install -dm00755 $installdir$PREFIX
    cp -a build/linux/work/* $installdir$PREFIX

    # install arduino-builder
    cp $BUILDER_DIR/arduino-builder $installdir$PREFIX
    cp -a $BUILDER_DIR/hardware/* $installdir$PREFIX/hardware

    # install arduino-ctags
    cd $CTAGS_DIR
    install -dm00755 $installdir$PREFIX/tools-builder/ctags/$CTAGS_VERSION
    cp ctags $installdir$PREFIX/tools-builder/ctags/$CTAGS_VERSION/

    # remove empty dirs and unnecessary install/uninstall scripts
    rm -rf $installdir$PREFIX/{reference,hardware/arduino/avr/extras,install.sh,uninstall.sh,arduino-linux-setup.sh}

    # make symlink and .desktop file for arduino
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/usr/share/pixmaps
    install -dm00755 $installdir/usr/share/applications
    ln -s $PREFIX/arduino $installdir/usr/bin/arduino
    ln -s $PREFIX/lib/icons/256x256/apps/arduino.png $installdir/usr/share/pixmaps/arduino.png
    sed -i "s,<BINARY_LOCATION>,arduino %U,g;s,<ICON_NAME>,arduino,g" $installdir$PREFIX/lib/desktop.template
    mv $installdir$PREFIX/lib/desktop.template $installdir/usr/share/applications/arduino.desktop
